version: "3.7"
services:
  jupyterlab-server:
    build:
      args:
        - username=${USER}
        - uid=${UID}
        - gid=${GID}
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
            - ${HOST_DATA_DIR}:${DEST_DATA_DIR}
            - ${HOST_RESULTS_DIR}:${DEST_RESULTS_DIR}
            - ${HOST_NOTEBOOK_DIR}:${DEST_NOTEBOOK_DIR}
    ports:
      - "8888:8888"
    init: true
    stdin_open: true
    tty: true

